version: '3'
services:
  postgres:
    image: postgres:16
    ports:
      - "5555:5432"
    environment:
      - "POSTGRES_DB=acb"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: backend
    environment:
      - "POSTGRES_HOST=172.17.0.1"
      - "POSTGRES_PORT=5555"
      - "POSTGRES_NAME=acb"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
