# Generated by Django 5.0.4 on 2024-04-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.BigIntegerField(db_index=True)),
                ('team_id', models.BigIntegerField(blank=True, null=True)),
                ('player_license_id', models.BigIntegerField(blank=True, null=True)),
                ('player_points', models.IntegerField(blank=True, null=True)),
                ('player_rebounds', models.IntegerField(blank=True, null=True)),
                ('action_time', models.TimeField(db_index=True)),
                ('action_type', models.IntegerField(db_index=True)),
                ('is_home_team', models.BooleanField()),
                ('score_home_team', models.IntegerField()),
                ('score_away_team', models.IntegerField()),
            ],
        ),
    ]
