# Generated by Django 5.0.4 on 2024-04-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchEventActionType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("normalized_description", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("team_id", models.BigIntegerField()),
                ("player_license_id", models.BigIntegerField()),
                ("action_time", models.DurationField()),
                (
                    "action_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="match_event.matcheventactiontype"
                    ),
                ),
            ],
        ),
    ]
