# Generated by Django 5.0.4 on 2024-04-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("match_event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchevent",
            name="game_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
